### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by WorldWonderful10** [BeneficialCode/WinArk#3]
Could be interest a File Manager with Delete/Force Delete features like [**PC Hunter**](https://www.majorgeeks.com/files/details/pc_hunter.html) (old **XueTr**) :D

**Comment by BeneficialCode** [comment]
Could you recommend some open source repos about File Manager ? Then I can choose one to integrate in WinArk.

**Comment by nblog** [comment]
proven program with suggested references:
[mohuihui/antispy -> FileDlg](https://github.com/mohuihui/antispy/blob/master/src/Antispy/SpyHunter/SpyHunter/FileDlg.cpp#L152)

for individual effects, refer to (MFC):
https://www.codeproject.com/Articles/12766/File-tree-control-allowing-selection-of-multiple-f

for forced file deletion, I provide some references:
[kernel irp](https://github.com/mohuihui/antispy/blob/master/src/Antispy/SpyHunterDrv/SpyHunterDrv/DeleteFile.c#L1030)
[kernel delete or unlock](https://github.com/DragonQuestHero/Kernel-Force-Delete/blob/master/Kernel_Force_Delete/Kernel_Force_Delete.cc#L199)
[ring3 unlock](https://github.com/ez8-co/unlocker)

hope this helps.

**Comment by BeneficialCode** [comment]
I really appreciate it. Actually I just a little lazy, I have finished the file management ui. The irp code also includes in the kernel library.

**Comment by BeneficialCode** [comment]
The force delete file function completed.
