### ISSUE TITLE
按照编译文档编译错误

### ISSUE THREAD

**Issue by hhuiwang** [BeneficialCode/WinArk#7]
请教您的Poco版本是多少？？，我的环境配置都完成，该安装的库都已经安装编译。最后编译WinArk.exe时一直找不到符号。也不知道这几个符号的哪个lib库的，实在头大啊。

1>PocoNetmt.lib(IPAddress.cpp.obj) : error LNK2001: 无法解析的外部符号 __std_count_trivial_1
1>PocoFoundationmt.lib(File.cpp.obj) : error LNK2001: 无法解析的外部符号 _Thrd_sleep_for
1>PocoFoundationmt.lib(AsyncChannel.cpp.obj) : error LNK2001: 无法解析的外部符号 _Thrd_sleep_for
1>D:\github\WinArk\x64\Release\WinArk.exe : fatal error LNK1120: 2 个无法解析的外部命令

**Comment by BeneficialCode** [comment]
poco 1.12.4, vcpkg 你可以把vs自带的vcpkg卸载掉，git clone vcpkg仓库的试试。

**Comment by hhuiwang** [comment]
![QQ截图20240627194826](https://github.com/BeneficialCode/WinArk/assets/33827101/37b9a2c2-ca62-44da-8e46-82b611b303f0)
搞了两天，终于编译出来了，原因是 vcpkg install poco[netssl]:x64-windows-static 安装这个库的时候自动找到了VS2022去编译的，之后要用VS2022打开工程才能编译。但是我现在不想用2022，想请教一下vcpkg install的时候如何才能让它使用vs2019呢？？？
![QQ截图20240627195346](https://github.com/BeneficialCode/WinArk/assets/33827101/9065deff-d702-45d6-8a42-88db96f74287)
cmake默认版本已经设置成功，但是这个 vcpkg还是抽风的去找到了2022

**Comment by BeneficialCode** [comment]
卸载vs2022自带的vcpkg
